Added Abstract Function to allow changing the UserLocationMarkerIcon
bmw-tech/atlas pull request #76
Opened 2020-04-30 13:53 UTC by Rloaded

Added Abstract Function to allow changing the UserLocationMarkerIcon.

(mostly affecting the here-atlas)

2020-05-04 15:03 UTC, tchabot22 submitted a review, later dismissed

2020-05-04 15:51 UTC, dakrawczyk requested changes
as part of this PR, please

1. increase the version (it seems this is a minor change) 
2. update the changelog

2020-05-12 10:07 UTC, oguibueno approved these changes

2020-05-12 15:39 UTC, tchabot22 approved these changes

2020-05-12 15:46 UTC, dakrawczyk reviewed
how will this work for map providers that do not support changing the UserLocationIcon? Will they be able to not override this method? or return nothing from this method?

2020-05-12 16:31 UTC, oguibueno commented
> how will this work for map providers that do not support changing the UserLocationIcon? Will they be able to not override this method? or return nothing from this method?

Since it's an abstract class (interface) I believe that all the clients who implements it will need to do something like: 

```
 @override
  void changeUserLocationIcon(String asset) {
    // TODO: implement changeUserLocationIcon
  }
```

We'll also need to update [google_atlas](https://github.com/bmw-tech/atlas/tree/master/packages/google_atlas) to support this new method.

2020-05-12 16:33 UTC, dakrawczyk approved these changes

2020-05-12 16:34 UTC, merged