Upgrade to support flutter 1.17.1
bmw-tech/atlas pull request #80
Opened 2020-05-26 15:10 UTC by afrueh

- Version bump of google_atlas to 0.4.0
- Upgrade RxDart to 0.24.1

Example:
- Upgrade flutter_bloc to 4.0.0

2020-05-26 18:47 UTC, dakrawczyk approved these changes

2020-05-27 16:28 UTC, tchabot22 submitted a review, later dismissed

2020-05-27 18:52 UTC, dakrawczyk requested changes
Hey @afrueh, as part of this PR can you include the changelog entry and version bump required?

2020-05-28 16:34 UTC, dakrawczyk approved these changes

2020-06-03 01:45 UTC, tchabot22 approved these changes

2020-09-25 16:56 UTC, edsondiasalves commented
Supporting flutter 1.20 in this merged PR: https://github.com/bmw-tech/atlas/pull/97

2020-09-25 16:56 UTC, closed without merging